on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Codecov Workflow
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov .
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}